# Uncomment the next line to define a global platform for your project
# platform :ios, '12.2'

target 'SearchTestApp' do
   	pod 'SnapKit', '~> 5.0.1'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'Alamofire', '~> 5.0.0-rc.1'
  use_frameworks!

  # Pods for SearchTestApp

end
